const USER_NOT_FOUND="user not found";
const SOMETHING_WENT_WRONG="Something went wrong"
const SOMETHING_WENT_WRONG_WHILE_SIGN_IN= `${SOMETHING_WENT_WRONG} while signin`
const NOT_AUTHENTICATED= "NOT_AUTHENTICATED"

export {USER_NOT_FOUND,SOMETHING_WENT_WRONG,SOMETHING_WENT_WRONG_WHILE_SIGN_IN,NOT_AUTHENTICATED}